<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>DatadrivenSuite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>256db9c9-7c42-486f-b499-053d70e57cf9</testSuiteGuid>
   <testCaseLink>
      <guid>1abf2cc5-206d-4dd0-8a18-fd2b2d522f23</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/katalondemo</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>b8b03551-7f7c-44aa-80a7-846e75f6c968</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/UserAdd</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>b8b03551-7f7c-44aa-80a7-846e75f6c968</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>FirstName</value>
         <variableId>6969817a-561d-495a-ac57-116469bb5fa1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>b8b03551-7f7c-44aa-80a7-846e75f6c968</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>LastName</value>
         <variableId>0a6591a6-04a8-45e3-98c6-5c0ff5ce615b</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
