<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>testsuitekatalon</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>fd491c6c-4402-40da-8c37-2c41db40eca3</testSuiteGuid>
   <testCaseLink>
      <guid>290a2600-086f-442e-982f-924a1bf9b2ba</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/katalondemo</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>4cac2d05-c71f-4357-b8f3-01dc3f0c89c9</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/tesdb</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>4cac2d05-c71f-4357-b8f3-01dc3f0c89c9</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>FirstName</value>
         <variableId>6969817a-561d-495a-ac57-116469bb5fa1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>4cac2d05-c71f-4357-b8f3-01dc3f0c89c9</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>LastName</value>
         <variableId>0a6591a6-04a8-45e3-98c6-5c0ff5ce615b</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
